### ISSUE TITLE
try decodeUriComponent

### ISSUE THREAD

**Issue by ZooeyMiller** [FACG2/Books_Auto-Completer#37]
In [`handleSearch`](https://github.com/FACG2/Books_Auto-Completer/blob/master/src/handlers.js#L26-L30) you are using a (really cool!) regex. Javascript has some inbuilt stuff for encoding and decoding urls, which are a little more reliable than writing your own versions. Check out [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) and [decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent)

**Comment by Sohadwd** [comment]
We used it, thanks.

**Comment by ZooeyMiller** [comment]
Awesome! :+1:
